
export const FETCH_ADMIN_LOGIN_REQUEST = "FETCH_ADMIN_LOGIN_REQUEST";
export const FETCH_ADMIN_LOGIN_SUCCESS = "FETCH_ADMIN_LOGIN_SUCCESS";
export const FETCH_ADMIN_LOGIN_FAILURE = "FETCH_ADMIN_LOGIN_FAILURE";
export const FETCH_ADMIN_REGISTER_REQUEST = "FETCH_ADMIN_REGISTER_REQUEST";
export const FETCH_ADMIN_REGISTER_SUCCESS = "FETCH_ADMIN_REGISTER_SUCCESS";
export const FETCH_ADMIN_REGISTER_FAILURE = "FETCH_ADMIN_REGISTER_FAILURE";
export const LOGOUT = "LOGOUT";